import Head from 'next/head'
import Landing from '../components/Landing/Landing'

export default function Home() {
  return (
    <div className="max_width">
      <Head>
        <title>baadaye</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <>
        <Landing />
      </>
    </div>
  )
}
